#Verbs
READ = 'READ:'
SET = 'SET:'
#Locations
SAMPLE = 'DEV:DB8.T1:TEMP:'
PT2 = 'DEV:DB7.T1:TEMP:'
VTI = 'DEV:MB1.T1:TEMP:'
NV = 'DEV:DB5.P1:PRES:'

#Actions
CURRENT_TEMP = 'SIG:TEMP'
CURRENT_PRES = 'SIG:PRES'
SETPT_TEMP = 'LOOP:TSET'
SETPT_PERC = 'LOOP:FSET'
AUTO_SET = 'LOOP:FAUT'

#Shortcuts
READ_VERSION='READ:SYS:MAN:HVER'
READ_ALARMS='READ:SYS:ALRM'
READ_NV_PERC = 'READ:DEV:DB4.G1:AUX:SIG:PERC'
