#Verbs
READ = 'READ:'
SET = 'SET:'
#Locations
SAMPLE = 'DEV:DB8.T1:TEMP:'
VTI = 'DEV:DB7.T1:TEMP'
PT2 = 'DEV:MB1.T1:TEMP'
NV = 'DEV:DB5.P1:PRES'

#Actions
CURRENT_TEMP = 'SIG:TEMP'
CURRENT_PRES = 'SIG:PRES'
SETPT_TEMP = 'LOOP:TSET'
SETPT_PRES = 'LOOP:FSET'
AUTO_SET = 'LOOP:FAUT'